services:
  musicbot:
    build:
      context: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./sessions:/app/sessions
      - /data/IntHDD/Navidrome/temp:/app/temp
      - /data/IntHDD/Navidrome/music:/app/music
